jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  datasource:
    url: ENC(SR+/jlo9H1CE5PVJ4mBsjK90zqeh+s6RX46nBrDULqYdMPgOfndZBAW2+jLbpxfgN44lxsKTOIX3oPaXKCSFBMtfNhf7TwXqELl7lZPylOApzmQ64oAJShzmUM8QfC54)
    username: ENC(S+As9Z4E6n5oT2dIFkgDQqkfHH9iwARx)
    password: ENC(apqTmfN8I1/j0cPtMXyxJGilGUpz6l/4)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

# 카카오 로그인
oauth:
  kakao:
    client-id: ENC(2ZfCUVXei11fTmOnBqtLqjAnEm1nK/ogiRg4NSDiGoDPUMvMfwpkO0h14ph5b9vs)

# JWT
jwt:
  secret: ENC(8NEpnmhCTRlaUv9EScYdkT3czu2ociz/tFqusPWVuWLQm0YZoGPIWRW5f2OnWd9r+2P8+ihWumC6IUCPfC2NYZ3ARz8PgQ0iZjR7O2C0EyI+EGWgZvNvbhTMN2UwYYoZV44BbQhioNtbZcYyNEGQrxSh8H7T4OiHtpn/TJzeXmqNlAiixxJV6Xz0J2YxJKXT)
  access-token-time: ENC(GS/+4wj+/UhdiLcHEraIX2MiDVdUYE07)
  refresh-token-time: ENC(DGbVhdWv3CDOp9QIlJpCfHDUibIJpn8A)