jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  datasource:
    url: ENC(SR+/jlo9H1CE5PVJ4mBsjK90zqeh+s6RX46nBrDULqYdMPgOfndZBAW2+jLbpxfgN44lxsKTOIX3oPaXKCSFBMtfNhf7TwXqELl7lZPylOApzmQ64oAJShzmUM8QfC54)
    username: ENC(S+As9Z4E6n5oT2dIFkgDQqkfHH9iwARx)
    password: ENC(apqTmfN8I1/j0cPtMXyxJGilGUpz6l/4)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true